# UCS420: Cognitive Computing — Assignment 4: NumPy Introduction-1

*Note:* the questions ask for variables named after you (`<<Your Name>>`). Change `NAME` below and, if you
want the exact variable names, rename `yourname` / `ucs420_yourname` with Find & Replace.

In [1]:
import numpy as np
NAME = "yourname"

## Q1. Basic operations on a 1-D array

In [2]:
a = np.array([4, 8, 12, 16, 20])
print("original     :", a)
print("a) + 2       :", a + 2)
print("b) * 3       :", a * 3)
print("c) / 2       :", a / 2)

original     : [ 4  8 12 16 20]
a) + 2       : [ 6 10 14 18 22]
b) * 3       : [12 24 36 48 60]
c) / 2       : [ 2.  4.  6.  8. 10.]


## Q2. Basic array questions

In [3]:
# a) reverse
arr = np.array([1, 2, 3, 6, 4, 5])
print("a) reversed:", arr[::-1])          # also: np.flip(arr)

a) reversed: [5 4 6 3 2 1]


In [4]:
# b) most frequent value(s) and their indices (ties handled: every value with the max count is reported)
def most_frequent(a):
    values, counts = np.unique(a, return_counts=True)
    top = counts.max()
    for v in values[counts == top]:
        print(f"   value {v} occurs {top} times at indices {np.where(a == v)[0]}")

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print("b-i)  x:"); most_frequent(x)
print("b-ii) y (1 and 3 tie):"); most_frequent(y)

b-i)  x:
   value 1 occurs 5 times at indices [0 5 7 8 9]
b-ii) y (1 and 3 tie):
   value 1 occurs 3 times at indices [0 1 2]
   value 3 occurs 3 times at indices [4 8 9]


## Q3. Accessing 2-D elements
(The question's array is missing the outer brackets — `np.array([10,20,30],[40,50,60],...)` is a syntax/argument
error; the correct form is a list of lists.)

In [5]:
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
print("a) 1st row, 2nd column :", arr2[0, 1])     # 20
print("b) 3rd row, 1st column :", arr2[2, 0])     # 70

a) 1st row, 2nd column : 20
b) 3rd row, 1st column : 70


## Q4. `linspace` array, its attributes, and transpose

In [6]:
yourname = np.linspace(10, 100, 25)
print(yourname)
print("dimensions (ndim):", yourname.ndim)
print("shape            :", yourname.shape)
print("total elements   :", yourname.size)
print("dtype            :", yourname.dtype)
print("total bytes      :", yourname.nbytes, "(= size x itemsize =", yourname.size, "x", yourname.itemsize, ")")

# transpose using reshape(): turn the 1-D array into a column (25 x 1)
col = yourname.reshape(25, 1)
print("\nreshape(25, 1) shape:", col.shape)
print("reshape(1, 25) shape:", yourname.reshape(1, 25).shape, "-> its .T is", yourname.reshape(1, 25).T.shape)

# using .T directly on the 1-D array
print("\nyourname.T shape:", yourname.T.shape, "| unchanged?", np.array_equal(yourname.T, yourname))

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions (ndim): 1
shape            : (25,)
total elements   : 25
dtype            : float64
total bytes      : 200 (= size x itemsize = 25 x 8 )

reshape(25, 1) shape: (25, 1)
reshape(1, 25) shape: (1, 25) -> its .T is (25, 1)

yourname.T shape: (25,) | unchanged? True


**Can we do the same with `.T`?** Not on a 1-D array. A transpose reverses the order of the axes; a 1-D array has
only one axis, so `yourname.T` returns the same `(25,)` array. To get a column vector you must add an axis first:
`reshape(25, 1)` (or `yourname[:, None]`), or first make it 2-D — `yourname.reshape(1, 25).T` — and then `.T` works.

## Q5. 2-D array `ucs420_<name>`: statistics, reshape, resize

In [7]:
ucs420_yourname = np.array([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 15, 20, 35]])
print("array (3x4):\n", ucs420_yourname)
print("mean   :", ucs420_yourname.mean())
print("median :", np.median(ucs420_yourname))
print("max    :", ucs420_yourname.max())
print("min    :", ucs420_yourname.min())
print("unique :", np.unique(ucs420_yourname), "(20 appears twice, so 11 unique values out of 12)")

# reshape -> 4 rows x 3 columns (same 12 elements, new layout)
reshaped_ucs420_yourname = ucs420_yourname.reshape(4, 3)
print("\nreshaped_ucs420_yourname (4x3):\n", reshaped_ucs420_yourname)

# resize -> 2 rows x 3 columns (6 elements: np.resize keeps the first 6 values in order, rest are dropped)
resized_ucs420_yourname = np.resize(ucs420_yourname, (2, 3))
print("\nresized_ucs420_yourname (2x3):\n", resized_ucs420_yourname)

array (3x4):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
mean   : 43.333333333333336
median : 37.5
max    : 90
min    : 10
unique : [10 15 20 30 35 40 50 60 70 80 90] (20 appears twice, so 11 unique values out of 12)

reshaped_ucs420_yourname (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

resized_ucs420_yourname (2x3):
 [[10 20 30]
 [40 50 60]]


**reshape vs resize:** `reshape` only rearranges the same number of elements (12 → 4x3) and returns a view when
possible; `resize` can change the total size — shrinking drops trailing elements (as here), growing repeats the data.